---
applicationName: gateway

containerImage:
  repository: slavashagalov/car-rental-gateway
  tag: latest
  pullPolicy: Always

containerPorts:
  http:
    port: 80
    protocol: TCP

startupProbe:
  httpGet:
    path: /manage/health
    port: http
  failureThreshold: 30
  periodSeconds: 3

livenessProbe:
  httpGet:
    path: /manage/health
    port: http

readinessProbe:
  httpGet:
    path: /manage/health
    port: http

lifecycleHooks:
  enabled: false

replicaCount: 1

service:
  enabled: true
  ports:
    app:
      port: 80
      targetPort: http
      protocol: TCP

ingress:
  enabled: true
  ingressClassName: nginx
  path: /
  pathType: Prefix
  servicePort: app

envVars:
  WEB_PORT: 80
  carsApiAddr: "http://cars-api"
  rentalApiAddr: "http://rental-api"
  paymentApiAddr: "http://payment-api"
