logging:
  level: -4 # -4: debug, 0: info, 4: warn, 8: error
kafka:
  addresses:
    - kafka:9092
  topic: "statistics"
db:
  driverName: postgres
  connectionString: postgres://program:test@postgres:5432/requests?sslmode=disable
