name: GitHub Classroom Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Install app dependencies
        run: go mod tidy

      - name: Build gateway
        run: go build -v ./cmd/gateway/main.go

      - name: Build cars service
        run: go build -v ./cmd/car/main.go

      - name: Build rental service
        run: go build -v ./cmd/rental/main.go

      - name: Build payment service
        run: go build -v ./cmd/payment/main.go

      - name: Build retryer worker
        run: go build -v ./cmd/retryer/main.go

  unit_test:
    name: Unit Test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run unit tests for gateway
        run: go test -v ./internal/gateway/...

  api_test:
    name: API Test
    needs: [ unit_test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU for Docker build
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run API Tests
        timeout-minutes: 5
        run: ./scripts/test-script.sh
        env:
          SERVICE_NAME: payment-api
          PORT_NUMBER: 8050

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v

  push_images:
    needs: [ api_test ]
    name: Push images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU for Docker build
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Push images
        timeout-minutes: 10
        run: |
          docker push slavashagalov/car-rental-gateway:latest
          docker push slavashagalov/car-rental-retryer:latest
          docker push slavashagalov/car-rental-cars-api:latest
          docker push slavashagalov/car-rental-rental-api:latest
          docker push slavashagalov/car-rental-payment-api:latest
